### ISSUE TITLE
Which WA API?

### ISSUE THREAD

**Issue by lisaalaz** [rakutentech/MathSensei#1]
Hi, thank you for your work on MathSensei. Could you clarify which of the WolframAlpha APIs was used for obtaining the results in the paper? Is it the LLM API? Many thanks

**Comment by debobanerjee** [comment]
We used the Free API (2000 non-commercial free calls per month) : https://products.wolframalpha.com/api
![Screenshot_20240901_231508_Chrome.jpg](https://github.com/user-attachments/assets/987a3cb3-1e76-48c4-8361-901baafc31bc)
